/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameStarter;

import apphelper.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author michael.roy-diclemen
 */
public class SplashPanel extends javax.swing.JPanel {

    GameModel gm;
    Sound music = new Sound("audio/WiiSports.wav");
    Sprite bg = new Sprite(0,0,"images/yourimage.jpg",Const.WIDTH,Const.HEIGHT);
    Text introText = new Text("Welcome to my game", 10,50);

    /**
     * Creates new form IntroPanel
     */
    public SplashPanel(GameModel g) {
        initComponents();
        //sets preferred size of the panel
        setPreferredSize(new Dimension(Const.WIDTH, Const.HEIGHT));
        //set up game Model
        gm = g;
        //configure intro text
        introText.setFont(Const.LARGE_FONT);
        introText.setClr(Color.red);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        introButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        playButton.setText("Play Game");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        introButton.setText("Intro");
        introButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(introButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(playButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introButton)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
                music.stop();
                CardLayout cl = (CardLayout) gm.mainPanel.getLayout();
        cl.show(gm.mainPanel, "game");
    }//GEN-LAST:event_playButtonActionPerformed

    private void introButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introButtonActionPerformed
                music.stop();
        CardLayout cl = (CardLayout) gm.mainPanel.getLayout();
        cl.show(gm.mainPanel, "intro");      // TODO add your handling code here:
    }//GEN-LAST:event_introButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        music.start();
        music.loop();       
    }//GEN-LAST:event_formComponentShown
public void paintComponent(Graphics g){
    super.paintComponent(g);
    bg.draw(g);
    introText.draw(g);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton introButton;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
