/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ridefactory;

import apphelper.Sprite;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author amirb
 */
public class SplashPanel extends javax.swing.JPanel {
    
    //Create background sprite
    Sprite theBackground = new Sprite(0, 0, "images/Background.png", 1920, 1080);
    Sprite logo = new Sprite(367, 172, "images/RFLogo.png",1186, 593);
    
    //Font
    Font customFont1;
    
    //For sharing information
    InformationStored in;
    /**
     * Creates new form SplashPanel
     */
    public SplashPanel(InformationStored info) {
        initComponents();
        //Set the preffered size of panel
        setPreferredSize(new Dimension(1920,1080));
        //Set up info model
        in = info;

        //Set the bounds of the button
        jButton2.setBounds(819, 771, 282, 106);
        
        //Implementing font. Code adapted from https://stackoverflow.com/questions/5652344/how-can-i-use-a-custom-font-in-java
        final GraphicsEnvironment GE = GraphicsEnvironment.getLocalGraphicsEnvironment();
        try {
            final File fontFile = new File("fonts/Anonymous Pro B.ttf");
            customFont1 = Font.createFont(Font.TRUETYPE_FONT, fontFile);
            GE.registerFont(customFont1);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        //The code below sets the buttons font
        if (customFont1 != null) {
            jButton2.setFont(customFont1.deriveFont(Font.PLAIN, 35)); // Use customFont
        } else {
            System.err.println("Custom font is null. Unable to set font.");
        }
        
    }
    
    //Getter for jButton2
    public JButton getLoginButton() {
        return jButton2;
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        //Draws the background
        theBackground.draw(g);
        //Draws the logo
        logo.draw(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(241, 240, 236));
        jButton2.setText("Login");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton2.setPreferredSize(new java.awt.Dimension(282, 106));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 771, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    //If Login it hit, move to next screen
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        CardLayout cl = (CardLayout) in.mainPanel.getLayout();
        cl.show(in.mainPanel, "vinSearch");
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
