/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ridefactory;

import apphelper.Sound;
import apphelper.Sprite;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;



/**
 *
 * @author amirb
 */
public class VinSearchPanel extends javax.swing.JPanel {
    //Set Background
    Sprite theBackground = new Sprite(0, 0, "images/Background.png", 1920, 1080);
    
    InformationStored in;
    
    //Font
    Font customFont2;
    
    //Initializing GamePanel
    GamePanel gp;
    
    //Intialize sound effect for game start
    Sound gameStartSound = new Sound("audio/gameStartSound.wav");
    
    
    /**
     * Creates new form VinSearchPanel
     */
    public VinSearchPanel(InformationStored info) {
        initComponents();
        setPreferredSize(new Dimension(1920,1080));
        //Set up info model
        in = info;
       
        
        //Implementing font. Code adapted from https://stackoverflow.com/questions/5652344/how-can-i-use-a-custom-font-in-java
        final GraphicsEnvironment GE = GraphicsEnvironment.getLocalGraphicsEnvironment();
        try {
            final File fontFile = new File("fonts/Anonymous Pro B.ttf");
            customFont2 = Font.createFont(Font.TRUETYPE_FONT, fontFile);
            GE.registerFont(customFont2);
        } catch (FontFormatException | IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        //The code below sets all the items fonts to the custom font
        if (customFont2 != null) {
            jLabel2.setFont(customFont2.deriveFont(Font.PLAIN, 54));
            jLabel3.setFont(customFont2.deriveFont(Font.PLAIN, 34));
            jLabel4.setFont(customFont2.deriveFont(Font.PLAIN, 34));
            jLabel5.setFont(customFont2.deriveFont(Font.PLAIN, 34));
            jLabel6.setFont(customFont2.deriveFont(Font.PLAIN, 54));
            jLabel1.setFont(customFont2.deriveFont(Font.PLAIN, 54));
            jTextField1.setFont(customFont2.deriveFont(Font.PLAIN, 34));
            jButton1.setFont(customFont2.deriveFont(Font.PLAIN, 35));
            jButton2.setFont(customFont2.deriveFont(Font.PLAIN, 35));
        } else {
            System.err.println("Custom font is null. Unable to set font.");
        }
        
        
        //Manually had to add this code since I am having issues with
        //the NetBeans drag and drop section
        jButton1.setText("Start");
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        //Draws the background
        theBackground.draw(g);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Your Boost:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 801, -1, -1));

        jTextField1.setBackground(new java.awt.Color(241, 240, 236));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField1.setPreferredSize(new java.awt.Dimension(1149, 81));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 297, -1, -1));

        jLabel2.setText("Enter Your VIN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 178, -1, -1));

        jLabel3.setText("Depending on the car you enter, you will gain a boost.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 411, -1, -1));

        jLabel4.setText("You can find your car's VIN by looking at the driver side of the front");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 582, -1, -1));

        jLabel5.setText("windshield, or by checking inside the doors.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 636, -1, -1));

        jLabel6.setText("Your Car:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 716, -1, -1));

        jButton1.setBackground(new java.awt.Color(241, 240, 236));
        jButton1.setText("Enter");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton1.setPreferredSize(new java.awt.Dimension(282, 107));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 920, -1, -1));

        jButton2.setBackground(new java.awt.Color(241, 240, 236));
        jButton2.setText("Enter");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton2.setPreferredSize(new java.awt.Dimension(282, 107));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1293, 284, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    //When Start button is pressed, move to main game screen
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        //Plays the game start sound effect then waits 5 seconds for the sound effect to fully play
        try{
            gameStartSound.start();
            Thread.sleep(3500);
        } catch (InterruptedException e) {
            System.out.print(e);
        }
        
        //Create new gamePanel
        gp = new GamePanel(in);
        //Save gamePanel in info so that cash label can be changed by partsPanel
        in.gamePanel = gp;
        //Add gp to CardLayout
        in.mainPanel.add(gp, "game");
        //Switches to main game panel
        CardLayout cl = (CardLayout) in.mainPanel.getLayout();
        cl.show(in.mainPanel, "game");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        //Get the vin the user entered
        String vin = jTextField1.getText().toUpperCase();
        
        //The code below has been put together from a multitude of different sources
        //Initialize client
        OkHttpClient client = new OkHttpClient();
        
        //Make an array of every country and the brands part of that country
        String[] germanBrands = 
        {"AUDI", "BMW", "MERCEDES-BENZ", "PORSCHE", "VOLKSWAGEN"};
        
        String[] americanBrands = 
        {"CHEVROLET", "FORD", "GMC", "DODGE", "JEEP", "CHRYSLER", "CADILLAC", "BUICK"};

        String[] southKoreanBrands = 
        {"HYUNDAI", "KIA", "GENESIS"};

        String[] japaneseBrands = 
        {"TOYOTA", "HONDA", "NISSAN", "SUBARU", "MAZDA", "LEXUS", "ACURA", "INFINITI"};

        String[] britishBrands = 
        {"ASTON MARTIN", "BENTLEY", "JAGUAR", "LAND ROVER", "LOTUS", "MINI", "ROLLS-ROYCE"};

        String[] italianBrands = 
        {"ALFA ROMEO", "FERRARI", "FIAT", "LAMBORGHINI", "MASERATI"};

        String[] swedishBrands = 
        {"VOLVO", "KOENIGSEGG"};
        
        
        //Write out request input URL
        String theurl = "https://mc-api.marketcheck.com/v2/decode/car/" + vin + "/specs?api_key=f5f4fb2c-f158-480b-9c45-c437d75149ec";
        
        //Build a request
        Request request = new Request.Builder()
                .get()
                .url(theurl)
                .build();
        
        client.newCall(request).enqueue(new Callback() {
            //If there was an issue making call
            @Override
            public void onFailure(Call call, IOException e) {
                e.printStackTrace();
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                //If response is able to be recieved, save the reponse
                if (response.isSuccessful()) {
                    String responseBody = response.body().string();
                    
                    // Use Gson library to parse JSON
                    Gson gson = new Gson();
                    JsonObject jsonObject = gson.fromJson(responseBody, JsonObject.class);
                    
                    // Extract make and model
                    String make = jsonObject.get("make").getAsString().toUpperCase();
                    String model = jsonObject.get("model").getAsString();
                    
                    jLabel6.setText("Your Car: " + make + " " + model);
                    
                    //Apply the corresponding boost depending on what country the
                    //player's car is from
                    for (String s: germanBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Precision Engineering");
                            in.vinBoost = 1;
                        }
                    }
                    
                    for (String s: americanBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Government Loan");
                            in.vinBoost = 2;
                        }
                    }
                    
                    for (String s: southKoreanBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Smart Spending");
                            in.vinBoost = 3;
                        }
                    }
                    
                    for (String s: japaneseBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Mass Production");
                            in.vinBoost = 4;
                        }
                    }
                    
                    for (String s: britishBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Status Symbol");
                            in.vinBoost = 5;
                        }
                    }
                    
                    for (String s: italianBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Status Symbol");
                            in.vinBoost = 5;
                        }
                    }
                    
                    for (String s: swedishBrands) {
                        if (s.equals(make)) {
                            jLabel1.setText("Your Boost: Precision Engineering");
                            in.vinBoost = 1;
                        }
                    }
                } else {
                    //On request failure, get error
                    System.out.println("Error: " + response.code() + " " + response.message());
                    jLabel3.setText("Error getting VIN");
                }
            }
        });
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
